### ISSUE TITLE
Language Files

### ISSUE THREAD

**Issue by MysticCity** [MysticCity/Ancient#169]
Alle Texte in eine Language File packen

**Comment by Th3Shadowbroker** [comment]
@MysticCity ich schlage  vor, für einige Sprachen Übersetzen auf bukkit zu rekrutieren.

Konzept des Language-Systems steht bereits:

- [X]Enum für Language-Codes
- [ ]Language-File Objekt
- [ ]Language-Config (NUR zum einstellen des Language-Codes)

**Comment by Th3Shadowbroker** [comment]
Aktueller stand: https://github.com/MysticCity/Ancient/commit/91cc12f3a1205f7206a942ba4f045890558da44e

**Comment by Th3Shadowbroker** [comment]
Auch hier: System steht, Übersetzung in Progress im Rahmen des Remakes
