### ISSUE TITLE
Spell damage ignore HP system (Critical) 

### ISSUE THREAD

**Issue by MysticCity** [MysticCity/Ancient#17]
What steps will reproduce the problem?
1. if i attack enemy with spell like lightning strike then mob died instantly - because mob have 20hp (in config 2000)
2. if i attack enemy with sword than with lightning strike then all ok - mob have 1900 hp like in config

What is the expected output? What do you see instead?
Need some fix for HP system or Damage Command fix

What version of the product are you using?
ARPG build #54 (16.04.2013 18:57:20)
mcpc-plus-1.4.7-R1.1-SNAPSHOT-f534-0

Do you have an error log of what happened?
No errors

Please provide any additional information below.
Need fix for 1.4.7 (not for 1.5.1)

Das Problem habe ich auch:
Mob hat 200 leben.
Skill sollte 100 Schaden machen, sind einige monster 1hit einige nicht.
Alles zufällig gesteuert.

**Comment by FroznMine** [comment]
Geht das jetzt? Müsste eigentlich oder?

**Comment by MysticCity** [comment]
dazu kann ich nichts sagen da die spells ja alle nicht gehen

zu deinen fragen:
Kein Error nein
Es wird einfach nicht gecastet
und danach wenn ich es erneut testen will sagt er cooldown ist aktiv

**Comment by FroznMine** [comment]
Okay....
