### ISSUE TITLE
MythicMobs Support

### ISSUE THREAD

**Issue by MysticCity** [MysticCity/Ancient#176]
We got this Error:
[20:58:00 ERROR]: [Ancient] Plugin Ancient v1.1 has failed to register events for class com.ancientshores.Ancient.Listeners.External.MythicMobsListene
r because net/elseland/xikage/MythicMobs/API/Events/MythicMobSpawnEvent does not exist.

We use Your last and MM last Version.

**Comment by FroznMine** [comment]
Sieht so aus als hätten die in 2.1.0 den Code komplett umstrukturiert. Werde da MM aktualisieren und dann das alles korrigieren

**Comment by Th3Shadowbroker** [comment]
Updated class https://github.com/MysticCity/Ancient/blob/master-2016/src/com/ancientshores/Ancient/Listeners/External/MythicMobsListener.java
