### ISSUE TITLE
GUI System

### ISSUE THREAD

**Issue by MysticCity** [MysticCity/Ancient#178]
Alle Commands in eine schöne GUI verpacken

**Comment by Th3Shadowbroker** [comment]
Zu beginn werde ich erst einmal ein grundlegendes Interface schaffen :)

**Comment by Th3Shadowbroker** [comment]
Aktueller Status: https://github.com/MysticCity/Ancient/commit/368e506bf870f5bca4da39b83c7f46110ea46b11

**Comment by Th3Shadowbroker** [comment]
GUI-Systemkomponenten stehen.
Weiteres folgt separat.
