### ISSUE TITLE
Fehler beim * Zeichen

### ISSUE THREAD

**Issue by MysticCity** [MysticCity/Ancient#195]
http://pastebin.com/m07dmG69

**Comment by Th3Shadowbroker** [comment]
Das ist absolut logisch.
* equals multiply.
Das lässt sich genau so einfach beheben. 
Einfach die Eingabe als String.ValueOf(<Eingegebener Text>) deklarieren und fertig: https://github.com/MysticCity/Ancient/commit/bc5c8a9ab5cbd2383f0c41c061247d5f30e5cc47
