### ISSUE TITLE
Cooldowns resetting after relog 

### ISSUE THREAD

**Issue by MysticCity** [MysticCity/Ancient#67]
When there is a Cooldown on a Spell it will be resettet after relogg.
This means if a spell has 20Hours Cooldown you could get around this by relogging. This way you can ignore the cooldowns

Wenn ein Zauber einen Cooldown hat, dann kann man diesen umgehen in dem man sich neu einloggt. Mit einem Aus- und wieder Ein-Loggen werden alle Cooldowns auf 0 gesetzt.

**Comment by FroznMine** [comment]
Was passiert, wenn man den Server stoppt? Bleiben die Cooldowns dann erhalten?

**Comment by MysticCity** [comment]
nicht getestet
